<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<strong class="product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</strong>
<?php
if($block->escapeHtml($product->getIsPreOrder()) == "1") {
    ?>
    <strong class="product-item-preorder" style="background-color: #F3F3F3">
        <span style="padding: 5px; border-radius: 2px; font-size: 12px;">Pre Order</span>
    </strong>
<?php
}
?>
