<div id="shippingbar">
    <div id="shippingbar-block-list" data-bind="scope:'minicart-addons'" class="block">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script>
            freeShippingEligibleAmount = <?= $this->getFreeShippingAmount()?>;
        </script>
        <script type="text/x-magento-init">
         {
             "#shippingbar-block-list": {
                 "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
             },
             "*": {
                 "Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
             }
         }
     </script>
    </div>
</div>
