<div id="example-output" data-bind="scope: 'exampleScope'">
    <h3>Minicart contents</h3>
    <div data-bind="text: shoppingCartUrl"></div>
</div>

<script type="text/x-magento-init">
    {
        "#example-output": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "exampleScope": {
                        "component": "Training_Example/js/view/example"
                    }
                }
            }
        }
    }
</script>