<?php
ini_set("display_errors", "1");
error_reporting(E_ALL);
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use \Magento\Framework\App\Action\Action;

?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');

echo "<pre>";
print_r($_helper);exit;
?>
